language: python
python:
  - '2.7'
install:
  - pip install -r requirements/test.txt
  - python setup.py install
before_script:
  - flake8 . --max-line-length=120 --max-complexity=10 --exclude='docs,venv,env,*.egg'
script:
  - nosetests --cover-branches --with-coverage --cover-min-percentage=100 --cover-package=newrelic_api
